[project]
name = "retrieve-logan-contigs"
version = "0.1.0"
description = "Downloads contigs from a specified Logan assembly"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.8",
    "zstandard>=0.23.0",
]
